export default {
  app: "videos",
  commands: [
    {
      name: "library list",
      method: "GET",
      path: "/api/library",
      description:
        "List media, favorites, and saved groups; rescan=1 refreshes.",
      query: ["rescan"],
    },
    {
      name: "rescan",
      method: "POST",
      path: "/api/rescan",
      description: "Scan media; force=1 rereads metadata.",
      query: ["force"],
    },
    {
      name: "file get",
      method: "GET",
      path: "/api/file",
      description: "Download original bytes; use --output FILE or pipe stdout.",
      query: ["path"],
    },
    {
      name: "poster get",
      method: "GET",
      path: "/api/poster",
      description: "Download artwork/preview bytes; use --output FILE.",
      query: ["path"],
    },
    {
      name: "upload",
      method: "POST",
      path: "/api/upload",
      description: "Upload one or more media files.",
      body: "multipart",
    },
    {
      name: "video update",
      method: "PATCH",
      path: "/api/video",
      description: "Update metadata with {path, ...fields}.",
      body: "json",
    },
    {
      name: "video trash",
      method: "DELETE",
      path: "/api/video",
      description: "Move media to trash; repeat --path for multiple files.",
      query: ["path"],
    },
    {
      name: "favorite set",
      method: "POST",
      path: "/api/favorite",
      description: "Set {path, favorite}; false removes the favorite.",
      body: "json",
    },
    {
      name: "collections create",
      method: "POST",
      path: "/api/collections",
      description: "Create {name, paths?}.",
      body: "json",
    },
    {
      name: "collections update",
      method: "PATCH",
      path: "/api/collections/:id",
      description: "Update {name?, paths?}.",
      body: "json",
    },
    {
      name: "collections delete",
      method: "DELETE",
      path: "/api/collections/:id",
      description: "Delete the saved group.",
    },
    {
      name: "trash restore",
      method: "POST",
      path: "/api/trash",
      description: "Restore {batchId}.",
      body: "json",
    },
    {
      name: "trash empty",
      method: "DELETE",
      path: "/api/trash",
      description: "Permanently empty media trash.",
    },
    {
      name: "poster save",
      method: "POST",
      path: "/api/poster",
      description: "Save JPEG poster bytes from --file FILE.",
      query: ["path"],
      body: "bytes",
    },
    {
      name: "subtitles list",
      method: "GET",
      path: "/api/subtitles",
      description: "List sidecar subtitle tracks.",
      query: ["path"],
    },
    {
      name: "subtitle get",
      method: "GET",
      path: "/api/subtitle",
      description: "Download WebVTT subtitle text.",
      query: ["path"],
    },
    {
      name: "progress set",
      method: "POST",
      path: "/api/progress",
      description: "Save {path, time?, duration?, width?, height?, watched?}.",
      body: "json",
    },
  ],
};
